# ───────────────────── ActionBar ─────────────────────
actionbar:
  enabled: true  # true/false para activar o desactivar ActionBar

  messages:
    - "&7ᴍᴄ.ᴡᴀᴛᴏɴᴇꜱ.ɴᴇᴛ"
    # - "&dTienda: &ftienda.watones.net"
    # - "&dDiscord: &fdiscord.gg/watones"

  interval: 40

# ───────────────────── BossBar ───────────────────────
bossbar:
  enabled: true

  messages:
    - "&f25% de &dDESCUENTO &fen tienda.watones.net"
    - "&fIP: &dmc.watones.net"

  color: PINK
  style: SOLID
  rotation-interval: 200

  progress:
    enabled: true
    initial: 1.0
    step: 0.01
    pingpong: true

# ───────────────────── Mundos objetivo ───────────────
worlds:
  - Lobby
